server:
    port: 8082
spring:
    application:
        name: sensemore-aistudio
    autoconfigure:
        exclude:
            - org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration
            - org.springframework.ai.model.openai.autoconfigure.OpenAiAudioTranscriptionAutoConfiguration
            - org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration
            - org.springframework.ai.model.openai.autoconfigure.OpenAiImageAutoConfiguration
            - org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
            - org.springframework.ai.model.openai.autoconfigure.OpenAiModerationAutoConfiguration
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:./data/testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
        username: root
        password: test
    h2:
        console:
            enabled: true
            path: /h2-console #http://localhost:8082/h2-console
    sql:
        init:
            schema-locations: classpath:db/schema-h2.sql
            data-locations: classpath:db/data-h2.sql
            mode: never
            platform: h2
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
